### ISSUE TITLE
docker-compose up fails on puppetserver

### ISSUE THREAD

**Issue by Cinderhaze** [puppetlabs/puppet-in-docker-examples#10] opened 2016-10-24 03:18 UTC
While trying to run docker-compose up from the compose example directory, the following error is encountered.

```
puppet              | 2016-10-24 02:35:50,600 INFO  [p.s.j.jruby-pool-manager-service] Initializing the JRuby service                                                              [1505/1707]
puppet              | 2016-10-24 02:35:50,636 INFO  [p.s.j.i.jruby-internal] Creating JRubyInstance with id 1.
puppetboard_1       | [2016-10-24 02:35:58 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
puppetboard_1       | [2016-10-24 02:35:58 +0000] [8] [INFO] Worker exiting (pid: 8)
puppetboard_1       | [2016-10-24 02:35:58 +0000] [9] [INFO] Booting worker with pid: 9
puppet              | 2016-10-24 02:36:00,329 INFO  [puppetserver] Puppet Puppet settings initialized; run mode: master
puppet              | 2016-10-24 02:36:02,665 ERROR [puppetserver] Puppet Could not set 'directory' on ensure: Permission denied - /opt/puppetlabs/server/data/puppetserver/state
puppet              | org/jruby/RubyDir.java:458:in `mkdir'
puppet              | /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file/ensure.rb:91:in `set_directory'
puppet              | /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:142:in `withumask'
puppet              | /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file/ensure.rb:90:in `set_directory'
```

chmod -R 777 ./puppet allows the run to continue, to get around the user/uid inside/outside container mismatch problem.  Should there be a rake task or some documentation in the readme on how to handle this problem for people who are new to containers?

**Comment by v1v** [comment] 2016-11-02 16:14
I've seen this error only if you run in Linux, but using MacOSX no errors at all

**Comment by underscorgan** [comment] 2018-05-21 21:16
Apologies for the delay in getting to this, but thank you for the report. 

I've been unable to reproduce this failure with either osx or centos 7, so I'm going to close this now. If this is still an issue can you open a ticket at https://tickets.puppet.com/browse/CPR with the 'Container' component? We're migrating away from GitHub issues.

**Closed by underscorgan** 2018-05-21 21:16 UTC
